#' Use INLA for autoregressive time series prediction by group
#'
#' @export
grouped_inla_ts <- function(df,
                            group_col = "iso3",
                            formula = value ~ INLA::f(year_n, model = "ar1"),
                            family = "gaussian",
                            control.predictor = list(compute = TRUE),
                            control.inla = list(strategy = "laplace"),
                            ...,
                            ret = c("df", "all", "error", "model"),
                            test_col = NULL,
                            pred_col = "pred",
                            upper_col = "upper",
                            lower_col = "lower",
                            filter_na = c("predictors", "response", "all", "none"),
                            type_col = NULL,
                            types = c("imputed", "imputed", "projected"),
                            type_group = "iso3",
                            type_sort = "year",
                            source_col = NULL,
                            source = NULL,
                            replace_obs = c("missing", "all", "none"),
                            error_correct = FALSE,
                            error_correct_cols = NULL) {
  grouped_predict_inla(df = df,
                       group_col = group_col,
                       formula = formula,
                       family = family,
                       control.predictor = control.predictor,
                       control.inla = control.inla,
                       ...,
                       ret = ret,
                       test_col = test_col,
                       pred_col = pred_col,
                       upper_col = upper_col,
                       lower_col = lower_col,
                       filter_na = filter_na,
                       type_col = type_col,
                       types = types,
                       type_group = type_group,
                       type_sort = type_sort,
                       source_col = source_col,
                       source = source,
                       replace_obs = replace_obs,
                       error_correct = error_correct,
                       error_correct_cols)
}

#' Use INLA for mixed effects modeling for prediction
#'
#' @export
predict_inla_me <- function(df,
                            formula = value ~ sdi_scaled + e0_scaled + INLA::f(region, model = 'iid') + INLA::f(year_n, model = "rw2"),
                            family = "gaussian",
                            control.predictor = list(compute = TRUE),
                            control.inla = list(strategy = "laplace"),
                            ...,
                            ret = c("df", "all", "error", "model"),
                            test_col = NULL,
                            pred_col = "pred",
                            upper_col = "upper",
                            lower_col = "lower",
                            filter_na = c("predictors", "response", "all", "none"),
                            type_col = NULL,
                            types = c("imputed", "imputed", "projected"),
                            type_group = "iso3",
                            type_sort = "year",
                            source_col = NULL,
                            source = NULL,
                            replace_obs = c("missing", "all", "none"),
                            error_correct = TRUE,
                            error_correct_cols = "iso3") {
  predict_inla(df = df,
               formula = formula,
               family = family,
               control.predictor = control.predictor,
               control.inla = control.inla,
               ...,
               ret = ret,
               test_col = test_col,
               pred_col = pred_col,
               upper_col = upper_col,
               lower_col = lower_col,
               filter_na = filter_na,
               type_col = type_col,
               types = types,
               type_group = type_group,
               type_sort = type_sort,
               source_col = source_col,
               source = source,
               replace_obs = replace_obs,
               error_correct = error_correct,
               error_correct_cols)
}
